### ISSUE TITLE
Is there any reason why there's CancellationToken in every controller action?

### ISSUE THREAD

**Issue by bugproof** [nbarbettini/BeautifulRestApi#11]
Those actions are mostly short-running. Does it add any benefit?

**Comment by nbarbettini** [comment]
Good point, it's probably not as useful with how short-running these actions are. I wanted to demonstrate the correct pattern of passing a CancellationToken through the layers from ASP.NET Core -> actions -> database/network code. It certainly can be removed if you don't need to handle cancellation mid-request.

**Comment by bugproof** [comment]
So it's not that useful in this case? Alright ;)
