### ISSUE TITLE
wiki/docs: link to Ion is broken 

### ISSUE THREAD

**Issue by jkone27** [nbarbettini/BeautifulRestApi#12]
I cannot navigate to this link : https://ionwg.org/ via chrome.

ionwg.org uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by nbarbettini** [comment]
The Ion spec site changed to https://ionspec.org. Thanks for the reminder to update the readme.

Was there anywhere other than the readme that you noticed this problem? I think I fixed all the occurrences. Let me know if I didn't.
