### ISSUE TITLE
Implement Commands separate from Queries

### ISSUE THREAD

**Issue by alexandrudanpop** [nbarbettini/BeautifulRestApi#2]
Hi, really nice tutorial, appreciate your contribution!

I would suggest one change: 
CreateUserQuery
CreatePostQuery
Use CreateUserCommand and CreatePostCommand naming instead.

If you want to approach a CQRS design maybe also separate queries from commands using an abstract interface for each of them. 
Cheers!

**Comment by nbarbettini** [comment]
That's a great suggestion. When I circle back to working on this again, I'll definitely consider it.

**Comment by nbarbettini** [comment]
It's been a while, sorry to zombie this issue!

I significantly refactored the example project, and dropped the query/command stuff. I thought it would be better to show a more familiar services pattern, instead of my poor attempt to understand and implement CQRS. 😄
