### ISSUE TITLE
Api Consistency

### ISSUE THREAD

**Issue by altunbas-huseyin** [nbarbettini/BeautifulRestApi#3]
First of all thank you.
A great tutorial.
I suggest you take a look at this link.

https://www.devtrends.co.uk/blog/wrapping-asp.net-web-api-responses-for-consistency-and-to-provide-additional-information

**Comment by nbarbettini** [comment]
Thanks for the suggestion! The link is for ASP.NET 4.x, not ASP.NET Core, so the code doesn't really apply, but the idea of wrapping responses is pretty close to what the base [Resource class](https://github.com/nbarbettini/BeautifulRestApi/blob/master/src/Models/Resource.cs) does.
