### ISSUE TITLE
Getting Issue to opening the SLN file to VS2015..

### ISSUE THREAD

**Issue by abhishekbhalani** [nbarbettini/BeautifulRestApi#5]
Solution file not opening. Did you created over 2017 VS?

**Comment by nbarbettini** [comment]
I did create the solution in VS 2017.

What is the error you're getting?

**Comment by nbarbettini** [comment]
Since .NET Core support in VS 2015 is iffy, I'd definitely recommend VS 2017 ([Community Edition](https://www.visualstudio.com/downloads/) is free and works fine).

Closing this issue - let me know if you have further problems @abhishekbhalani.
