### ISSUE TITLE
Question about Lynda course

### ISSUE THREAD

**Issue by ghost** [nbarbettini/BeautifulRestApi#6]
I have enjoyed your course on Lynda.com building and securing restful api in asp.net core.  I was hopping this is the same project because I got a 500 error trying to get the token using the final project!  I would appreciate if you try it and let me know how I fix it.
Thanks

**Comment by nbarbettini** [comment]
This isn't quite the same project, but it contains many of the same principles and ideas.

Are you getting any 500s when running this project specifically?

**Comment by ghost** [comment]
Thank you, will continue using email.
